//! Action pinning: every program a CI run of this repo executes is named by
//! something that cannot change underneath it, and every checkout is handed
//! the least it can do the job with.
//!
//! The workflows are the one part of this repo no compiler reads. `uses:
//! owner/repo@v4` hands whoever owns that tag the right to change what runs
//! here — a tag is mutable, so a tag pin is a standing authorisation — and
//! that is not hypothetical: refs had drifted onto a moving `@v4`, a moving
//! `@v2`, a re-pointable `@v7.0.1` and a branch `@stable` while `ci.yml`'s
//! header still said "Every `uses:` here is commit-pinned". The sentence was
//! the whole enforcement. `zizmor.yml` now holds the rule as configuration and
//! `just zizmor` runs it; this test states the same rule where `just test`
//! reaches it, so it also holds with no zizmor on the machine, and it keeps
//! holding if a future `ignore:` entry ever silences that audit.
//!
//! The credential half is the same claim about what a step is *handed* rather
//! than what it runs. `actions/checkout` leaves a usable token in
//! `.git/config` unless told otherwise, so without `persist-credentials:
//! false` every later step in the job — and every action any of them calls —
//! holds push access to this repository that none of them needs.
//!
//! Why a test and not only a `just` recipe: both facts are decidable from
//! files already in the tree, so they need no gate of their own to argue with,
//! and `just ci` runs `just test`.

#![forbid(unsafe_code)]

use std::collections::BTreeSet;
use std::fs;
use std::path::{Path, PathBuf};

// ---------------------------------------------------------------------------
// the rules
// ---------------------------------------------------------------------------

/// How long a git commit is, spelled once.
const SHA_LEN: usize = 40;

/// Files exempt from carrying a human-readable version beside the pin, with
/// the reason. This is an exemption from the *annotation* and never from the
/// pinning — the refs in the file below are checked like every other.
const VERSION_COMMENT_EXEMPT: &[(&str, &str)] = &[(
    "release.yml",
    "generated by cargo-dist, which emits bare commits; `dist plan` fails on a hand-added comment",
)];

/// A floor under the refs found per file, so this cannot pass by having
/// stopped reading. A step written in a shape the line scanner does not
/// recognise otherwise turns the whole test green.
///
/// The list is checked in both directions. It has to be: a floor is a claim
/// about ONE file, so a file nobody added a line for has a floor of nothing
/// and the "the scan is still reading" half never applied to it. `audit.yml`
/// arrived with five `uses:` and three checkouts and would have been in
/// exactly that state — pinned by the scan today, and free to stop being read
/// tomorrow with every test still green.
const USES_FLOOR: &[(&str, usize)] = &[
    // Five to seven, and one to two on release-pins.yml below: the three
    // scheduled jobs that reported nowhere each call the local
    // `report-failure` action now. A floor tracks the file as it is.
    (".github/workflows/audit.yml", 7),
    // ci.yml fell from 20 to 14 when eleven hand-written jobs collapsed into
    // one matrix generated from the Justfile's `[group('gate')]`, and from 14
    // to 12 when the `changes` job went (#210) and took a checkout and the
    // paths-filter that classified the diff with it. Fewer jobs, not less
    // reading: a floor tracks the file as it is.
    (".github/workflows/ci.yml", 12),
    (".github/workflows/codeql.yml", 3),
    (".github/workflows/dependency-review.yml", 2),
    (".github/workflows/dev-image.yml", 5),
    (".github/workflows/docs.yml", 6),
    (".github/workflows/fuzz.yml", 3),
    (".github/workflows/labeler.yml", 1),
    (".github/workflows/publish-crates.yml", 5),
    (".github/workflows/release-pins.yml", 2),
    (".github/workflows/release.yml", 12),
    (".github/actions/setup-dev-image/action.yml", 3),
];

/// Same floor for the checkout scan: the credential rule is worth nothing if
/// the scanner finds no checkouts to apply it to. Fell from 20 to 18 with
/// ci.yml's gate matrix — seven jobs' worth of checkouts became one leg's —
/// and rose to 21 when audit.yml added three jobs, one checkout each. Left at
/// 21 against 22 present for the same one step of slack it has always carried.
const CHECKOUT_FLOOR: usize = 21;

/// Actions this repo pins at two different commits, each with why it is still
/// like that. Every entry is a LIVE DEFECT, not an exemption: an immutable pin
/// with no bump path is the failure that pinning trades for, and two copies at
/// two commits is how you find one that stopped being bumped.
const PIN_DRIFT: &[(&str, &str)] = &[(
    "docker/login-action",
    "`.github/actions/setup-dev-image/action.yml` is a whole major behind \
     `dev-image.yml` (v3 vs v4.5.2). Its three pins were set by hand in #65 and \
     have not moved since, while the workflow copies have been bumped several \
     times — Dependabot's `github-actions` ecosystem at `directory: \"/\"` is \
     not reaching `.github/actions/`. Bumping it is a major-version change to \
     the GHCR login and belongs in its own PR",
)];

/// Every audit `zizmor.yml` suppresses, and where. Each entry is a finding
/// this repo has decided not to fix *here* — a surviving defect with a
/// reason beside it in that file, not an absence of one. Pinned as a list
/// so adding a suppression is an edit somebody reviews, removing one is the
/// same, and the reader below cannot pass by parsing nothing.
const KNOWN_SUPPRESSIONS: &[(&str, &str)] = &[
    ("template-injection", "release.yml"),
    ("excessive-permissions", "release.yml"),
    ("unpinned-images", "release.yml"),
    ("dependabot-cooldown", "dependabot.yml"),
];

// ---------------------------------------------------------------------------
// reading a workflow without a YAML parser
// ---------------------------------------------------------------------------

/// One `uses:`, as written.
struct Uses {
    line: usize,
    reference: String,
    /// The `# v1.2.3` after the ref, if any.
    comment: Option<String>,
}

/// Indentation in columns. Workflows here are space-indented; a tab would be
/// an actionlint failure long before it reached this.
fn indent_of(line: &str) -> usize {
    line.len() - line.trim_start().len()
}

/// The value a line assigns to `key`, if it assigns one. `- uses: x` and
/// `uses: x` are the same assignment, the first merely opening a step.
fn key_value<'a>(line: &'a str, key: &str) -> Option<&'a str> {
    let body = line.trim_start();
    let body = body.strip_prefix("- ").map_or(body, str::trim_start);
    body.strip_prefix(key)?.strip_prefix(':').map(str::trim)
}

/// Split a `uses:` value from the trailing `# comment` annotating it.
fn split_trailing_comment(value: &str) -> (String, Option<String>) {
    value.split_once('#').map_or_else(
        || (value.trim().to_owned(), None),
        |(before, after)| (before.trim().to_owned(), Some(after.trim().to_owned())),
    )
}

fn uses_in(text: &str) -> Vec<Uses> {
    let mut out = Vec::new();
    for (index, raw) in text.lines().enumerate() {
        // A `#` opening the line is prose *about* a `uses:`, not one.
        if raw.trim_start().starts_with('#') {
            continue;
        }
        if let Some(value) = key_value(raw, "uses") {
            let (reference, comment) = split_trailing_comment(value);
            out.push(Uses {
                line: index + 1,
                reference,
                comment,
            });
        }
    }
    out
}

/// A `- ` list item and everything indented under it: one step, which is the
/// only structure this file needs out of YAML.
struct Block {
    line: usize,
    body: Vec<String>,
}

impl Block {
    fn assigns(&self, key: &str, value: &str) -> bool {
        self.body
            .iter()
            .any(|line| key_value(line, key) == Some(value))
    }

    fn uses_prefix(&self, prefix: &str) -> bool {
        self.body
            .iter()
            .filter_map(|line| key_value(line, "uses"))
            .any(|reference| reference.starts_with(prefix))
    }
}

fn blocks(text: &str) -> Vec<Block> {
    let mut out = Vec::new();
    let mut open: Option<Block> = None;
    let mut depth = 0usize;
    for (index, raw) in text.lines().enumerate() {
        let indent = indent_of(raw);
        // A non-blank line no deeper than the item's own dash ends it.
        if !raw.trim().is_empty()
            && indent <= depth
            && let Some(block) = open.take()
        {
            out.push(block);
        }
        // Only when nothing is open: a `- ` deeper than the current item is
        // that item's content (a `filters:` list, say), not the next step.
        if open.is_none() && raw.trim_start().starts_with("- ") {
            depth = indent;
            open = Some(Block {
                line: index + 1,
                body: Vec::new(),
            });
        }
        if let Some(block) = open.as_mut() {
            block.body.push(raw.to_owned());
        }
    }
    out.extend(open);
    out
}

// ---------------------------------------------------------------------------
// the verdicts
// ---------------------------------------------------------------------------

fn is_commit(git_ref: &str) -> bool {
    git_ref.len() == SHA_LEN && git_ref.chars().all(|ch| ch.is_ascii_hexdigit())
}

/// Why a `uses:` is not pinned, or `None` when it is.
fn pin_failure(reference: &str) -> Option<String> {
    // A path into this repository is already pinned: it is whatever the commit
    // under test contains, and nobody outside can re-point it.
    if reference.starts_with("./") {
        return None;
    }
    if let Some(image) = reference.strip_prefix("docker://") {
        return if image.contains("@sha256:") {
            None
        } else {
            Some(format!(
                "`docker://{image}` names a tag, not a digest: the registry can \
                 re-point it, so what runs in this job is not fixed by this file"
            ))
        };
    }
    let Some((action, git_ref)) = reference.rsplit_once('@') else {
        return Some(format!(
            "`{reference}` carries no `@ref` at all, so it resolves to whatever \
             the default branch holds the moment the job starts"
        ));
    };
    if is_commit(git_ref) {
        return None;
    }
    Some(format!(
        "`{action}@{git_ref}` is pinned to a ref its owner can move. Pinning is \
         not about the ref *looking* like a version, it is about it being \
         immutable: use the {SHA_LEN}-hex commit and put `# {git_ref}` beside it"
    ))
}

// ---------------------------------------------------------------------------
// one action's call sites, read together
// ---------------------------------------------------------------------------

/// One commit-pinned `uses:`: what GitHub resolves, and what a reader does.
struct Site {
    /// `owner/repo`, never the subpath. `github/codeql-action/init` and
    /// `github/codeql-action/analyze` are two `uses:` strings naming one
    /// repository at one tag — two observations of one pin, not two pins
    /// carrying one observation each, which is the state this file can say
    /// nothing about.
    repo: String,
    commit: String,
    /// The `# v1.2.3` beside the ref, where the file carries one.
    comment: Option<String>,
    /// `file:line`.
    at: String,
}

/// The `owner/repo` an action path names, dropping any subpath after it.
fn action_repo(action: &str) -> &str {
    action
        .match_indices('/')
        .nth(1)
        .map_or(action, |(slash, _)| &action[..slash])
}

/// Every commit-pinned `uses:` across `(label, contents)` pairs. Floating
/// refs are `every_action_this_repo_runs_is_named_by_an_immutable_commit`'s
/// to fail on; here they would be noise about a file that is already red.
fn sites_in(files: &[(String, String)]) -> Vec<Site> {
    let mut out = Vec::new();
    for (label, text) in files {
        for one in uses_in(text) {
            if let Some((action, git_ref)) = one.reference.rsplit_once('@')
                && is_commit(git_ref)
            {
                out.push(Site {
                    repo: action_repo(action).to_owned(),
                    commit: git_ref.to_owned(),
                    comment: one.comment,
                    at: format!("{label}:{}", one.line),
                });
            }
        }
    }
    out
}

/// What reading one repository's call sites against each other says.
#[derive(Debug)]
struct PinReport {
    /// One repo at two commits, minus the splits `PIN_DRIFT` records: a call
    /// site that has stopped being bumped with the others.
    drifted: Vec<String>,
    /// One commit under two version comments. Forty hex characters are one
    /// release, so at most one of the comments is true.
    mislabelled: Vec<String>,
    /// Every repo found at two commits, `PIN_DRIFT`'s included, so a recorded
    /// split can be held to still being one.
    split: BTreeSet<String>,
}

fn review_pins(sites: &[Site]) -> PinReport {
    let mut report = PinReport {
        drifted: Vec::new(),
        mislabelled: Vec::new(),
        split: BTreeSet::new(),
    };
    let repos: BTreeSet<&str> = sites.iter().map(|site| site.repo.as_str()).collect();

    for repo in repos {
        let mine: Vec<&Site> = sites.iter().filter(|site| site.repo == repo).collect();
        let commits: BTreeSet<&str> = mine.iter().map(|site| site.commit.as_str()).collect();

        if commits.len() > 1 {
            report.split.insert(repo.to_owned());
            if !PIN_DRIFT.iter().any(|&(name, _)| name == repo) {
                let where_at: Vec<&str> = mine.iter().map(|site| site.at.as_str()).collect();
                report.drifted.push(format!(
                    "  {repo} at {} commits: {where_at:?}",
                    commits.len()
                ));
            }
        }

        // Keyed per commit, not per repo, so this needs no `PIN_DRIFT`
        // exemption and gets none: a recorded split is two pins, each still
        // answerable for its own label. What it will not allow is one commit
        // answering to two.
        for commit in commits {
            let here: Vec<&&Site> = mine.iter().filter(|site| site.commit == commit).collect();
            let labels: BTreeSet<&str> = here
                .iter()
                .filter_map(|site| site.comment.as_deref())
                .collect();
            if labels.len() > 1 {
                let where_at: Vec<&str> = here.iter().map(|site| site.at.as_str()).collect();
                report.mislabelled.push(format!(
                    "  {repo}@{commit} is called {labels:?} at {where_at:?}"
                ));
            }
        }
    }
    report
}

/// Every `vN`, `vN.N` or `vN.N.N` a sentence names. A `v` inside a word
/// ("several", "rev2") is a letter, not a version.
fn versions_named_in(prose: &str) -> BTreeSet<&str> {
    let mut out = BTreeSet::new();
    for (start, _) in prose.match_indices('v') {
        if prose[..start]
            .chars()
            .next_back()
            .is_some_and(char::is_alphanumeric)
        {
            continue;
        }
        let tail = &prose[start + 1..];
        if !tail.starts_with(|ch: char| ch.is_ascii_digit()) {
            continue;
        }
        let end = tail
            .find(|ch: char| !ch.is_ascii_digit() && ch != '.')
            .unwrap_or(tail.len());
        out.insert(prose[start..=start + end].trim_end_matches('.'));
    }
    out
}

/// Recorded splits whose reason describes a tree that is no longer there. A
/// `PIN_DRIFT` entry is a bug report, and a bug report naming a version this
/// repo does not pin any more is one nobody can act on.
fn stale_reasons(sites: &[Site], drift: &[(&str, &str)]) -> Vec<String> {
    let mut out = Vec::new();
    for &(name, reason) in drift {
        let labels: BTreeSet<&str> = sites
            .iter()
            .filter(|site| site.repo == name)
            .filter_map(|site| site.comment.as_deref())
            .collect();
        for named in versions_named_in(reason) {
            if !labels.contains(named) {
                out.push(format!(
                    "  {name}: the reason says `{named}`, and the call sites are pinned at \
                     {labels:?}"
                ));
            }
        }
    }
    out
}

// ---------------------------------------------------------------------------
// the repo
// ---------------------------------------------------------------------------

fn repo_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("..").join("..")
}

/// Every YAML file under `.github/`: the workflows, the composite actions and
/// the configuration beside them. Recursive on purpose — a `uses:` in a
/// directory added tomorrow is in scope the moment it is written.
fn github_yaml(dir: &Path, out: &mut Vec<PathBuf>) {
    let mut entries: Vec<PathBuf> = fs::read_dir(dir)
        .into_iter()
        .flatten()
        .flatten()
        .map(|entry| entry.path())
        .collect();
    entries.sort();
    for path in entries {
        if path.is_dir() {
            github_yaml(&path, out);
        } else if path
            .extension()
            .is_some_and(|ext| ext == "yml" || ext == "yaml")
        {
            out.push(path);
        }
    }
}

/// `(repo-relative label, contents)` for every scanned file.
fn scanned_files(root: &Path) -> Vec<(String, String)> {
    let github = root.join(".github");
    assert!(github.is_dir(), "{} is gone", github.display());
    let mut paths = Vec::new();
    github_yaml(&github, &mut paths);
    paths
        .into_iter()
        .map(|path| {
            let label = path
                .strip_prefix(root)
                .unwrap_or(path.as_path())
                .display()
                .to_string();
            let text = fs::read_to_string(&path).unwrap_or_else(|e| panic!("reading {label}: {e}"));
            (label, text)
        })
        .collect()
}

/// Why a `(file, count)` scan fails its floors — in both directions. A floor
/// that names a file the scan never reached is a floor over nothing, and a
/// file the scan reached with no floor beside it is a file whose silence
/// nobody is holding to anything.
fn floor_failures(found: &[(String, usize)]) -> Vec<String> {
    let mut out = Vec::new();
    for &(file, floor) in USES_FLOOR {
        let seen = found
            .iter()
            .find(|(label, _)| label == file)
            .map_or(0, |&(_, count)| count);
        if seen < floor {
            out.push(format!(
                "{file}: {seen} `uses:` found, expected at least {floor}. The scan is \
                 reading less of the file than it used to, so its silence means nothing."
            ));
        }
    }
    for (label, count) in found {
        if *count == 0 || USES_FLOOR.iter().any(|&(file, _)| file == label) {
            continue;
        }
        out.push(format!(
            "{label}: {count} `uses:` found and no floor beside it. Add \
             (\"{label}\", {count}) to USES_FLOOR — until then this file is pinned only for as \
             long as the reader happens to understand it, and a step rewritten into a shape it \
             cannot parse unpins the file with nothing going red."
        ));
    }
    out
}

fn assert_floors(found: &[(String, usize)]) {
    let failures = floor_failures(found);
    assert!(
        failures.is_empty(),
        "the `uses:` scan is not covering what it is written over:\n{}",
        failures.join("\n")
    );
}

// ---------------------------------------------------------------------------
// the invariants
// ---------------------------------------------------------------------------

#[test]
fn every_action_this_repo_runs_is_named_by_an_immutable_commit() {
    let root = repo_root();
    let mut floating = Vec::new();
    let mut found = Vec::new();

    for (label, text) in scanned_files(&root) {
        let refs = uses_in(&text);
        found.push((label.clone(), refs.len()));
        for one in refs {
            if let Some(why) = pin_failure(&one.reference) {
                floating.push(format!("{label}:{}: {why}", one.line));
            }
        }
    }

    assert_floors(&found);
    assert!(
        floating.is_empty(),
        "actions not pinned to an immutable commit:\n{}",
        floating.join("\n")
    );
}

#[test]
fn every_commit_pin_says_which_version_it_is() {
    // A bare 40-hex is unreviewable: nobody can tell a routine bump from a
    // hijack by reading it, and that is the pressure that turns pins back into
    // tags. The comment is the readable half of the pin, so it is checked here
    // rather than requested in CONTRIBUTING.md.
    let root = repo_root();
    let mut bare = Vec::new();

    for (label, text) in scanned_files(&root) {
        if VERSION_COMMENT_EXEMPT
            .iter()
            .any(|&(file, _)| label.ends_with(file))
        {
            continue;
        }
        for one in uses_in(&text) {
            if one.reference.starts_with("./") || one.comment.is_some() {
                continue;
            }
            bare.push(format!(
                "{label}:{}: `{}` is pinned but unannotated — put `# v<version>` \
                 beside it so a bump can be reviewed",
                one.line, one.reference
            ));
        }
    }

    assert!(
        bare.is_empty(),
        "commit pins with no version comment:\n{}",
        bare.join("\n")
    );
}

#[test]
fn one_action_is_pinned_to_one_commit_across_the_whole_repo() {
    // The failure a pin buys: it cannot move on its own, so nothing notices
    // when it stops moving at all. Two call sites of one action are two
    // observations of the same pin, and a disagreement between them is the
    // only signal in the tree that one of the two is no longer maintained.
    let sites = sites_in(&scanned_files(&repo_root()));
    let report = review_pins(&sites);

    assert!(
        report.drifted.is_empty(),
        "one action, two commits — one of these call sites is not being bumped:\n{}\n\
         Pin both to the same commit, or record the split in PIN_DRIFT with the reason.",
        report.drifted.join("\n")
    );
    // The readable half of the same claim, and the half that fails first. A
    // version comment is what a reviewer bumps by, so one commit answering to
    // two of them is the split arriving before the SHAs move:
    // `taiki-e/install-action` sat at ONE commit under `# v2` in the composite
    // action and `# v2.81.10` in the workflows, which read as a deliberately
    // loose major pin and was in fact the only thing in the tree saying that
    // this call site is not on Dependabot's path. #229 then bumped the five
    // annotated `# v2.81.10` and left the one annotated `# v2` behind.
    assert!(
        report.mislabelled.is_empty(),
        "one commit, two version comments — a single pin described two ways:\n{}\n\
         Forty hex characters are one release, so at most one comment is true. \
         Put the version that commit actually is beside every copy.",
        report.mislabelled.join("\n")
    );
    // The other direction, so a recorded defect cannot outlive itself: an
    // entry here whose drift is gone is a bug report nobody closed.
    let healed: Vec<&str> = PIN_DRIFT
        .iter()
        .map(|&(name, _)| name)
        .filter(|name| !report.split.contains(*name))
        .collect();
    assert!(
        healed.is_empty(),
        "PIN_DRIFT records a split that no longer exists: {healed:?}. Delete the \
         entry — it is a defect that has been fixed."
    );
    // Nor can it outlive its own description. Bumping one side of a recorded
    // split is exactly the change that leaves the sentence describing it
    // stale, and a reason naming a version nobody pins any more is a bug
    // report about a tree that is gone.
    let stale = stale_reasons(&sites, PIN_DRIFT);
    assert!(
        stale.is_empty(),
        "PIN_DRIFT reasons that no longer describe this repo:\n{}\n\
         The entry is the whole record of why the split is allowed to stand. \
         Re-read it against the pins and say what is true now.",
        stale.join("\n")
    );
}

#[test]
fn every_checkout_drops_the_token_it_would_otherwise_leave_behind() {
    let root = repo_root();
    let mut leaking = Vec::new();
    let mut checkouts = 0usize;

    for (label, text) in scanned_files(&root) {
        for block in blocks(&text) {
            if !block.uses_prefix("actions/checkout@") {
                continue;
            }
            checkouts += 1;
            if !block.assigns("persist-credentials", "false") {
                leaking.push(format!(
                    "{label}:{}: this checkout keeps its token in `.git/config`, so \
                     every later step in the job inherits write access to the repo. \
                     Set `persist-credentials: false` under `with:`.",
                    block.line
                ));
            }
        }
    }

    assert!(
        checkouts >= CHECKOUT_FLOOR,
        "{checkouts} checkout steps found, expected at least {CHECKOUT_FLOOR}. \
         The scan is not seeing steps any more, so its silence means nothing."
    );
    assert!(
        leaking.is_empty(),
        "checkouts that persist credentials:\n{}",
        leaking.join("\n")
    );
}

#[test]
fn the_policy_file_still_states_the_rule_this_test_enforces() {
    // `zizmor.yml` and this file are one rule written twice, and two copies of
    // a rule drift. What can silently unmake the config half is an `ignore:`
    // under `unpinned-uses` — it reads like scoping and is a repeal — so the
    // policy is asserted here, where removing it fails rather than passes.
    let root = repo_root();
    let policy = root.join("zizmor.yml");
    let text =
        fs::read_to_string(&policy).unwrap_or_else(|e| panic!("reading {}: {e}", policy.display()));

    assert!(
        text.contains(r#""*": hash-pin"#),
        "zizmor.yml no longer carries the blanket `\"*\": hash-pin` policy, so a \
         `uses:` naming an action nobody listed is no longer covered by the config half"
    );

    let suppressions = rules_with_ignores(&text);
    assert!(
        !suppressions.iter().any(|(rule, _)| rule == "unpinned-uses"),
        "zizmor.yml ignores `unpinned-uses` somewhere. That audit IS the pinning \
         rule; scope it by policy, never by suppression."
    );

    let listed: Vec<(&str, &str)> = suppressions
        .iter()
        .map(|(rule, file)| (rule.as_str(), file.as_str()))
        .collect();
    assert_eq!(
        listed, KNOWN_SUPPRESSIONS,
        "the set of audits zizmor.yml suppresses has changed. Every one is a \
         finding this repo is choosing to live with, so the list belongs in \
         review — update KNOWN_SUPPRESSIONS and say why in zizmor.yml."
    );

    // A suppression that outlives its subject is a decision nobody can find
    // again. Each names a real file, or it goes.
    let present: BTreeSet<String> = scanned_files(&root)
        .into_iter()
        .filter_map(|(label, _)| {
            Path::new(&label)
                .file_name()
                .map(|name| name.to_string_lossy().into_owned())
        })
        .collect();
    let stale: Vec<String> = suppressions
        .iter()
        .filter(|(_, file)| !present.contains(file))
        .map(|(rule, file)| {
            format!("  {rule}: ignores `{file}`, which is not a file under .github/")
        })
        .collect();
    assert!(
        stale.is_empty(),
        "zizmor.yml suppressions that name nothing:\n{}",
        stale.join("\n")
    );
}

/// `(rule, ignored file)` for every `ignore:` entry in `zizmor.yml`, read the
/// way the rest of this file reads YAML: by indentation.
fn rules_with_ignores(text: &str) -> Vec<(String, String)> {
    let mut out = Vec::new();
    let mut rule = String::new();
    let mut in_ignore = false;
    for raw in text.lines() {
        let body = raw.trim();
        if body.is_empty() || body.starts_with('#') {
            continue;
        }
        if let Some(item) = body.strip_prefix("- ") {
            if in_ignore && !rule.is_empty() {
                out.push((rule.clone(), item.trim().to_owned()));
            }
            continue;
        }
        // Rule names sit one level under `rules:`, `ignore:` / `config:` one
        // level under a rule. Indentation is what tells the two apart.
        match indent_of(raw) {
            2 => {
                body.trim_end_matches(':').clone_into(&mut rule);
                in_ignore = false;
            }
            4 => in_ignore = body.starts_with("ignore:"),
            _ => {}
        }
    }
    out
}

// ---------------------------------------------------------------------------
// what the scan claims, pinned both ways
// ---------------------------------------------------------------------------

#[test]
fn a_floating_ref_is_reported_and_a_commit_is_not() {
    // The acceptance criterion, executable: adding a floating tag fails.
    let sha = "3d3c42e5aac5ba805825da76410c181273ba90b1";
    assert!(
        pin_failure(&format!("actions/checkout@{sha}")).is_none(),
        "a full commit was rejected"
    );
    for floating in [
        "actions/checkout@v7",
        "actions/checkout@v7.0.1",
        "dtolnay/rust-toolchain@stable",
        "github/codeql-action/init@v4",
        "taiki-e/install-action@v2",
        "actions/checkout",
    ] {
        assert!(
            pin_failure(floating).is_some(),
            "`{floating}` was accepted as pinned"
        );
    }
    // A short commit is not a commit: git resolves prefixes, and a prefix can
    // turn ambiguous — or be brute-forced into a collision — later.
    assert!(
        pin_failure(&format!("actions/checkout@{}", &sha[..7])).is_some(),
        "an abbreviated commit was accepted"
    );
    // Nor is 40 characters of something that is not hex.
    assert!(
        pin_failure(&format!("actions/checkout@{}", "z".repeat(SHA_LEN))).is_some(),
        "40 non-hex characters were accepted"
    );
}

/// `(label, contents)` pairs the way `scanned_files` returns them.
fn files(pairs: &[(&str, &str)]) -> Vec<(String, String)> {
    pairs
        .iter()
        .map(|&(label, text)| (label.to_owned(), text.to_owned()))
        .collect()
}

#[test]
fn one_commit_under_two_version_comments_is_reported() {
    // #229's precursor, as this repo actually held it for months.
    // `taiki-e/install-action` was at ONE commit across six call sites: five
    // workflows saying `# v2.81.10`, and the composite action — the one file
    // Dependabot's `directory: "/"` does not reach — saying `# v2`. Every
    // gate was green, and correctly so by its own question:
    // `one_action_is_pinned_to_one_commit_across_the_whole_repo` compared the
    // SHAs and they agreed, `every_commit_pin_says_which_version_it_is` asked
    // whether a comment was present and it was. Neither asked the two
    // comments to say the same thing, so the single difference the tree
    // recorded between the call sites Dependabot bumps and the one it cannot
    // see was the one thing nothing read.
    let sha = "7a79fe8c3a13344501c80d99cae481c1c9085912";
    let mixed = files(&[
        (
            ".github/workflows/ci.yml",
            &format!("      - uses: taiki-e/install-action@{sha}  # v2.81.10\n"),
        ),
        (
            ".github/actions/setup-dev-image/action.yml",
            &format!("    - uses: taiki-e/install-action@{sha} # v2\n"),
        ),
    ]);
    let report = review_pins(&sites_in(&mixed));
    assert!(
        report.drifted.is_empty(),
        "one commit was read as a split: {:?}",
        report.drifted
    );
    assert_eq!(
        report.mislabelled.len(),
        1,
        "one commit answering to both `v2` and `v2.81.10` passed"
    );

    // The other direction, or this fires on `release.yml` every run and
    // teaches the next reader that red is normal. An ABSENT comment is not a
    // disagreement: cargo-dist emits bare commits and `VERSION_COMMENT_EXEMPT`
    // is where that is argued, so nothing is claimed here to contradict.
    let bare = files(&[
        (
            ".github/workflows/fuzz.yml",
            &format!("      - uses: actions/upload-artifact@{sha}  # v7.0.1\n"),
        ),
        (
            ".github/workflows/release.yml",
            &format!("      - uses: actions/upload-artifact@{sha}\n"),
        ),
    ]);
    assert!(
        review_pins(&sites_in(&bare)).mislabelled.is_empty(),
        "an unannotated pin was read as disagreeing with an annotated one"
    );
}

#[test]
fn two_paths_into_one_action_repo_are_one_pin() {
    // `github/codeql-action/init` and `github/codeql-action/analyze` are two
    // `uses:` strings and one repository at one tag. Keyed by the `uses:`
    // path — as this file keyed them until now — they are two pins holding
    // one call site each, and a pin with one call site is the state this
    // whole invariant cannot speak about: the disagreement IS the signal. So
    // the exact defect the test exists to catch, one of two copies left
    // behind by a bump, walked through it whenever the two copies happened to
    // be spelled differently.
    assert_eq!(
        action_repo("github/codeql-action/init"),
        "github/codeql-action"
    );
    assert_eq!(action_repo("actions/checkout"), "actions/checkout");

    let old = "e4fba868fa4b1b91e1fdab776edc8cfbe6e9fb81";
    let new = "69366f33c96575abad1ee0dba8212993eecbe998";
    let half_bumped = files(&[(
        ".github/workflows/codeql.yml",
        &format!(
            "      - uses: github/codeql-action/init@{new}  # v4.38.0\n\
             \x20     - uses: github/codeql-action/analyze@{old}  # v4.37.3\n"
        ),
    )]);
    let report = review_pins(&sites_in(&half_bumped));
    assert_eq!(
        report.drifted.len(),
        1,
        "one action repo at two commits passed because its two call sites \
         spell different subpaths"
    );
    assert!(
        report.mislabelled.is_empty(),
        "two commits, each with its own version comment, were read as one \
         commit with two: {:?}",
        report.mislabelled
    );
}

#[test]
fn a_recorded_split_is_read_against_the_pins_it_describes() {
    // Versions, and only versions: a `v` inside a word is a letter.
    assert_eq!(
        versions_named_in(
            "a whole major behind (v3 vs v4.5.2). Set by hand in #65 and moved \
             several times since — a major-version change."
        ),
        BTreeSet::from(["v3", "v4.5.2"])
    );
    assert!(
        versions_named_in("every version of it, rev2, moved several times").is_empty(),
        "a letter inside a word was read as a version"
    );

    // The state #229 arrived in. Dependabot bumped `docker/login-action` on
    // one side of a split that `PIN_DRIFT` records, and could not know that a
    // sentence in a Rust file describes that split — so the entry went on
    // saying `v4.5.1` about a tree pinned at `v4.5.2`. `healed` above only
    // asks whether the split still exists; the reason is the entire argument
    // for why it is allowed to stand, and nothing read it.
    let three = "c94ce9fb468520275223c153574b00df6fe4bcc9";
    let four = "371161bbe7024a29a25c5e19bfcbc0804fe9ad2c";
    let both_sites = files(&[
        (
            ".github/workflows/dev-image.yml",
            &format!("        uses: docker/login-action@{four}  # v4.5.2\n"),
        ),
        (
            ".github/actions/setup-dev-image/action.yml",
            &format!("      uses: docker/login-action@{three} # v3\n"),
        ),
    ]);
    let sites = sites_in(&both_sites);
    assert!(
        stale_reasons(
            &sites,
            &[("docker/login-action", "a major behind (v3 vs v4.5.2)")]
        )
        .is_empty(),
        "a reason naming exactly the versions in the tree was reported stale"
    );
    assert_eq!(
        stale_reasons(
            &sites,
            &[("docker/login-action", "a major behind (v3 vs v4.5.1)")]
        )
        .len(),
        1,
        "a reason still naming the version from before the bump passed"
    );
}

#[test]
fn a_local_action_is_pinned_by_living_here_and_an_image_by_its_digest() {
    assert!(
        pin_failure("./.github/actions/setup-dev-image").is_none(),
        "a path into this repo was rejected"
    );
    assert!(
        pin_failure("docker://alpine@sha256:deadbeef").is_none(),
        "a digest-named image was rejected"
    );
    assert!(
        pin_failure("docker://alpine:3.20").is_some(),
        "a tag-named image was accepted"
    );
}

#[test]
fn a_uses_is_read_in_either_step_shape_and_prose_about_one_is_not() {
    let text = concat!(
        "      - uses: actions/checkout@1111111111111111111111111111111111111111  # v7.0.1\n",
        "      - name: Install Rust\n",
        "        uses: dtolnay/rust-toolchain@2222222222222222222222222222222222222222  # stable\n",
        "      # Every `uses:` here is commit-pinned, and zizmor.yml enforces it\n",
    );
    let found = uses_in(text);
    assert_eq!(found.len(), 2, "a comment about `uses:` was read as one");
    assert_eq!(
        found[0].comment.as_deref(),
        Some("v7.0.1"),
        "the version annotation was not split off"
    );
    assert_eq!(
        found[1].reference, "dtolnay/rust-toolchain@2222222222222222222222222222222222222222",
        "a `uses:` under `- name:` was read wrong"
    );
    assert_eq!(found[1].line, 3, "the reported line drifted");
}

#[test]
fn a_persist_credentials_setting_belongs_to_its_own_step() {
    // The mistake a line-at-a-time reader makes: one `persist-credentials:
    // false` anywhere in the file absolving every checkout in it. The nested
    // list is the other half — a `filters:` block must not end the step.
    let text = concat!(
        "    steps:\n",
        "      - uses: actions/checkout@1111111111111111111111111111111111111111\n",
        "        with:\n",
        "          filters: |\n",
        "            rust:\n",
        "              - 'crates/**'\n",
        "          persist-credentials: false\n",
        "      - uses: actions/checkout@1111111111111111111111111111111111111111\n",
        "        with:\n",
        "          fetch-depth: 0\n",
        "      - uses: ./.github/actions/setup-dev-image\n",
    );
    let verdicts: Vec<bool> = blocks(text)
        .iter()
        .filter(|block| block.uses_prefix("actions/checkout@"))
        .map(|block| block.assigns("persist-credentials", "false"))
        .collect();
    assert_eq!(
        verdicts,
        vec![true, false],
        "a step's setting leaked into its neighbour"
    );
}

#[test]
fn a_workflow_the_floor_list_forgot_is_reported() {
    // The half of the floor rule that did not exist until audit.yml was
    // written. A floor is per file, so the file nobody wrote a line for is the
    // one whose "the scan is still reading it" claim was never made — and that
    // is precisely the newly added workflow, i.e. the file most likely to be
    // written in a shape the reader does not yet handle.
    let clean: Vec<(String, usize)> = USES_FLOOR
        .iter()
        .map(|&(file, floor)| (file.to_owned(), floor))
        .collect();
    assert!(
        floor_failures(&clean).is_empty(),
        "every file at exactly its floor was reported: {:?}",
        floor_failures(&clean)
    );

    let mut forgotten = clean.clone();
    forgotten.push((".github/workflows/tomorrow.yml".to_owned(), 4));
    assert_eq!(
        floor_failures(&forgotten).len(),
        1,
        "a scanned file with no floor beside it passed"
    );

    let mut no_refs = clean.clone();
    no_refs.push((".github/dependabot.yml".to_owned(), 0));
    assert!(
        floor_failures(&no_refs).is_empty(),
        "a file the scan found no `uses:` in was asked for a floor; there is nothing there \
         for the scan to stop reading"
    );

    let mut gone = clean;
    gone[0].1 -= 1;
    assert_eq!(
        floor_failures(&gone).len(),
        1,
        "a file that fell below its floor passed"
    );
}
